In [1]:
import pandas as pd
import numpy as np

In [2]:
ambassadors = pd.Series([
    'France',
    'United, kingdom',
    'Germany'
    'United kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
],
    index=[
        'Gerard Araud',
        'Kim Darroch',
        'Peter Westmacott',
        'Armando Varricchio',
        'Peter Wittig',
        'Peter Ammon',
        'Klaus Scharioth'
    ]
)

In [3]:
ambassadors

Gerard Araud                         France
Kim Darroch                 United, kingdom
Peter Westmacott      GermanyUnited kingdom
Armando Varricchio                    Italy
Peter Wittig                        Germany
Peter Ammon                         Germany
Klaus Scharioth                     Germany
dtype: object

In [ ]:
ambassadors.duplicated()

Gerard Araud          False
Kim Darroch           False
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [ ]:
ambassadors.duplicated(keep= 'last')

Gerard Araud          False
Kim Darroch           False
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

In [ ]:
  ambassadors.duplicated(keep= False)

Gerard Araud          False
Kim Darroch           False
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [ ]:
ambassadors.drop_duplicates(keep = 'last')

Gerard Araud                         France
Kim Darroch                 United, kingdom
Peter Westmacott      GermanyUnited kingdom
Armando Varricchio                    Italy
Klaus Scharioth                     Germany
dtype: object

In [ ]:
ambassadors.drop_duplicates(keep = False)

Gerard Araud                         France
Kim Darroch                 United, kingdom
Peter Westmacott      GermanyUnited kingdom
Armando Varricchio                    Italy
dtype: object

In [4]:
ambassadors.drop_duplicates()

Gerard Araud                         France
Kim Darroch                 United, kingdom
Peter Westmacott      GermanyUnited kingdom
Armando Varricchio                    Italy
Peter Wittig                        Germany
dtype: object

In [6]:
#Duplicates in DataFrame
players = pd.DataFrame({
    'Name' : [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Pos' : [
        'SG',
        'SF',
        'SG',
        'SF',
        'SF'
    ]
})

In [7]:
players

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
2      Kobe Bryant  SG
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [8]:
players.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [9]:
players.duplicated(subset = ['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [10]:
players.duplicated(subset = ['Name'], keep = 'last')

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [28]:
#String Handling
df = pd.DataFrame({
    'Data' : [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_IT_1',
        '1985_F_IT_2',
    ]
})

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

In [21]:
df['Data'].str.split('_')

0    [1987, M, US , 1]
1    [1990?, M, UK, 1]
2     [1992, F, US, 2]
3    [1970?, M, IT, 1]
4     [1985, F, IT, 2]
Name: Data, dtype: object

In [15]:
df['Data'].str.split('_', expand= True)

       0  1    2  3
0   1987  M  US   1
1  1990?  M   UK  1
2   1992  F   US  2
3  1970?  M   IT  1
4   1985  F   IT  2

In [29]:
df = df['Data'].str.split('_', expand = True)

In [30]:
df.columns = ['Year', 'Sex', 'Country', 'No Children']

df

In [31]:
df['Year'].str.contains('\?')

0    False
1     True
2    False
3     True
4    False
Name: Year, dtype: bool

In [32]:
df['Country'].str.contains('U')

0     True
1     True
2     True
3    False
4    False
Name: Country, dtype: bool

In [33]:
df['Country'].str.strip()

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object

In [34]:
df['Country'].str.replace(' ', '')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object